    CREATE DATABASE IF NOT EXISTS voice_analysis;
    USE voice_analysis;
    CREATE TABLE IF NOT EXISTS voice (
            id INT AUTO_INCREMENT PRIMARY KEY,
            filename VARCHAR(255) NOT NULL,
            pitch FLOAT,
            energy FLOAT,
            zcr FLOAT,
            centroid FLOAT,
            bandwidth FLOAT,
            silence_ratio FLOAT,
            mfcc_1 FLOAT,
            mfcc_2 FLOAT,
            mfcc_3 FLOAT,
            mfcc_4 FLOAT,
            mfcc_5 FLOAT,
            mfcc_6 FLOAT,
            mfcc_7 FLOAT,
            mfcc_8 FLOAT,
            mfcc_9 FLOAT,
            mfcc_10 FLOAT,
            mfcc_11 FLOAT,
            mfcc_12 FLOAT,
            mfcc_13 FLOAT
        );
    CREATE TABLE IF NOT EXISTS voice_normalized (
            id INT AUTO_INCREMENT PRIMARY KEY,
            filename VARCHAR(255) NOT NULL,
            pitch FLOAT,
            energy FLOAT,
            zcr FLOAT,
            centroid FLOAT,
            bandwidth FLOAT,
            silence_ratio FLOAT,
            mfcc_1 FLOAT,
            mfcc_2 FLOAT,
            mfcc_3 FLOAT,
            mfcc_4 FLOAT,
            mfcc_5 FLOAT,
            mfcc_6 FLOAT,
            mfcc_7 FLOAT,
            mfcc_8 FLOAT,
            mfcc_9 FLOAT,
            mfcc_10 FLOAT,
            mfcc_11 FLOAT,
            mfcc_12 FLOAT,
            mfcc_13 FLOAT);